[project]
name = "ames-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "mlflow>=3.4.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]
